名称 = "导航球" = "navsphere"
兼容日期 = "2024-11-11" = "2024-11-11"
兼容性标志 = ["nodejs兼容"] = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static" = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23li4WJL4TV6N7fpHB" = "Ov23li4WJL4TV6N7fpHB"
GITHUB_OWNER = "suge168" = "suge168"
GITHUB_REPO = "NavSphere" = "NavSphere"
GITHUB_BRANCH = "main" = "main"
NEXTAUTH_URL = "https://nav666.pages.dev/api/auth" = "https://nav666.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://nav666.pages.dev"="nav666.pages.dev"

